/* ================================================================
   SVG ANIMATOR — CSS @keyframes Exporter
   Generates pure CSS animation and injects into SVG for export
   ================================================================ */
import { state, interpolateAtTime } from './app.js';

/**
 * Export the current SVG with all animations embedded as CSS @keyframes.
 * Returns the SVG string ready for download.
 */
export function exportAnimatedSVG() {
  if (!state.svgElement) return '';

  // ── Step 1: stamp live elements with a temp data attr so we can find
  //           them in the clone without relying on id (ids will be removed).
  for (const [elementId] of state.animations) {
    const info = state.elements.get(elementId);
    if (info) info.el.setAttribute('data-svga-export', elementId);
  }

  // ── Step 2: clone AFTER stamping
  const svg = state.svgElement.cloneNode(true);

  // Remove temp stamps from the live original right away
  for (const [elementId] of state.animations) {
    const info = state.elements.get(elementId);
    if (info) info.el.removeAttribute('data-svga-export');
  }

  // ── Step 3: clean preview styles from the clone
  svg.querySelectorAll('*').forEach(el => {
    el.style.transform = '';
    el.style.transformOrigin = '';
    el.style.opacity = '';
    el.style.fill = '';
    el.style.cursor = '';
    el.style.outline = '';
    el.style.outlineOffset = '';
    el.style.display = '';
    if (el.getAttribute('style') === '') el.removeAttribute('style');
  });

  // Remove any existing <style> blocks we may have added before
  svg.querySelectorAll('style[data-svganimator]').forEach(s => s.remove());

  // ── Step 4: generate CSS + class map
  const { css, classMap } = generateAllCSS();

  if (css) {
    // Add animation classes using the temp data attribute (not getElementById)
    for (const [elementId, className] of classMap) {
      const el = svg.querySelector(`[data-svga-export="${elementId}"]`);
      if (el) el.classList.add(className);
    }

    // Inject <style> into SVG
    const styleEl = document.createElementNS('http://www.w3.org/2000/svg', 'style');
    styleEl.setAttribute('data-svganimator', 'true');
    styleEl.textContent = '\n' + css;
    svg.insertBefore(styleEl, svg.firstChild);
  }

  // ── Step 5: strip ALL id attributes and temp data attrs from the clone
  //           so multiple SVGs on the same page never conflict.
  svg.querySelectorAll('[id]').forEach(el => el.removeAttribute('id'));
  svg.querySelectorAll('[data-svga-export]').forEach(el => el.removeAttribute('data-svga-export'));
  // Also remove the id from the root <svg> element itself if present
  svg.removeAttribute('id');

  // Serialize
  const serializer = new XMLSerializer();
  let svgString = serializer.serializeToString(svg);

  // Add XML declaration
  svgString = '<?xml version="1.0" encoding="UTF-8"?>\n' + svgString;

  return svgString;
}

/**
 * Generate all CSS @keyframes rules + animation declarations.
 * Returns { css: string, classMap: Map<elementId, className> }
 */
function generateAllCSS() {
  if (state.animations.size === 0) return { css: '', classMap: new Map() };

  let css = '/* Generated by SVG Animator — Pure CSS Animations */\n\n';
  const classMap = new Map();
  let counter = 1;
  const uniqueHash = Math.random().toString(36).substring(2, 8);

  for (const [elementId, tracks] of state.animations) {
    if (tracks.size === 0) continue;

    // Sequential class + keyframe names — with unique hash to prevent conflicts
    const className     = `svga-${uniqueHash}-${counter}`;
    const keyframeName  = `kf-${uniqueHash}-${counter}`;
    counter++;


    classMap.set(elementId, className);

    // Collect ALL unique time points across all tracks for this element
    const timeSet = new Set();
    for (const [, keyframes] of tracks) {
      for (const kf of keyframes) {
        timeSet.add(kf.time);
      }
    }
    // Always include 0 and duration endpoints
    timeSet.add(0);
    timeSet.add(state.duration);

    const times = [...timeSet].sort((a, b) => a - b);

    // ── Which property groups exist ──────────────────────────────
    const hasPosition = tracks.has('position');
    const hasScale    = tracks.has('scale');
    const hasRotate   = tracks.has('rotate');
    const hasSkew     = tracks.has('skew');
    const hasTransform = hasPosition || hasScale || hasRotate || hasSkew;
    const hasOrigin   = tracks.has('origin');
    const hasOpacity  = tracks.has('opacity');
    const hasFill     = tracks.has('fill');
    const hasMorph    = tracks.has('morph');

    // ── @keyframes block ─────────────────────────────────────────
    css += `@keyframes ${keyframeName} {\n`;

    for (const time of times) {
      const pct = state.duration > 0
        ? ((time / state.duration) * 100).toFixed(2)
        : '0.00';

      const lines = [];

      // Transform
      if (hasTransform) {
        const parts = [];

        if (hasPosition) {
          const v = interpolateAtTime(tracks.get('position'), time);
          if (v) parts.push(`translate(${round(v.x)}px, ${round(v.y)}px)`);
        }
        if (hasRotate) {
          const v = interpolateAtTime(tracks.get('rotate'), time);
          if (v !== null) parts.push(`rotate(${round(v)}deg)`);
        }
        if (hasScale) {
          const v = interpolateAtTime(tracks.get('scale'), time);
          if (v) parts.push(`scale(${round(v.x)}, ${round(v.y)})`);
        }
        if (hasSkew) {
          const v = interpolateAtTime(tracks.get('skew'), time);
          // skewX() and skewY() — skew() with two args is non-standard
          if (v) parts.push(`skewX(${round(v.x)}deg) skewY(${round(v.y)}deg)`);
        }

        if (parts.length > 0) {
          lines.push(`    transform: ${parts.join(' ')};`);
        }
      }

      // Transform-origin (animated, per-keyframe)
      if (hasOrigin) {
        const v = interpolateAtTime(tracks.get('origin'), time);
        if (v) lines.push(`    transform-origin: ${round(v.x)}px ${round(v.y)}px;`);
      }

      // Opacity
      if (hasOpacity) {
        const v = interpolateAtTime(tracks.get('opacity'), time);
        if (v !== null) lines.push(`    opacity: ${round(v / 100)};`);
      }

      // Fill
      if (hasFill) {
        const v = interpolateAtTime(tracks.get('fill'), time);
        if (v) lines.push(`    fill: ${v};`);
      }

      // Morph (d attribute via CSS — modern browsers)
      if (hasMorph) {
        const v = interpolateAtTime(tracks.get('morph'), time);
        if (v) lines.push(`    d: path("${v}");`);
      }

      if (lines.length > 0) {
        css += `  ${pct}% {\n${lines.join('\n')}\n  }\n`;
      }
    }

    css += `}\n\n`;

    // ── .className { animation: ...; transform-origin: ...; } ────
    css += `.${className} {\n`;
    css += `  animation: ${keyframeName} ${state.duration}s linear infinite;\n`;

    // transform-origin: if there is an origin track with one keyframe, use it.
    // Otherwise, derive bbox center from the live SVG element so scale/rotate
    // happen around the element's own center (not SVG 0,0).
    if (hasOrigin) {
      const originKfs = tracks.get('origin');
      if (originKfs.length === 1) {
        css += `  transform-origin: ${round(originKfs[0].value.x)}px ${round(originKfs[0].value.y)}px;\n`;
      }
    } else if (hasScale || hasRotate || hasSkew) {
      // Auto-compute bbox center from live element
      const info = state.elements.get(elementId);
      if (info && info.el.getBBox) {
        try {
          const bbox = info.el.getBBox();
          const cx = round(bbox.x + bbox.width  / 2);
          const cy = round(bbox.y + bbox.height / 2);
          css += `  transform-origin: ${cx}px ${cy}px;\n`;
        } catch (_) { /* getBBox may fail for hidden elements */ }
      }
    }

    css += `}\n\n`;
  }

  return { css, classMap };
}

function round(n) {
  return Math.round(n * 1000) / 1000;
}
